name: HotWheels Stock Check

on:
  schedule:
    - cron: '0 7 * * *'
    - cron: '0 15 * * *'
  workflow_dispatch:

jobs:
  check-stock:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          cd hw-check  # ← ДОБАВЬ ЭТУ СТРОЧКУ
          pip install -r requirements.txt
          
      - name: Run HotWheels Monitor
        run: |
          cd hw-check  # ← И ЭТУ СТРОЧКУ
          python src/bot.py
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
